spring:
  application:
    name: springboot-project-seed
  profiles:
    active: '@environment@'  #注意YAML配置文件需要加单引号，否则会报错

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:log/logback-spring.xml
